sudo: false
language: python
dist: focal
python:
  - "3.10"
install: pip install tox-travis
script: tox
after_success:
  - pip install python-semantic-release
  - git config user.name botcerts
  - git config user.email botcerts@learningmachine.com
  - semantic-release publish
after_script:
  - nvm install 16
  - node -v
  - which node
  - npm -v
  - which npm
  - which python3
  - sh prepare-vc-compliance-tests-config.sh
  - python3 setup.py install
  - npm i --force
  - npm run test:vc-compliance
#  - strace -f -s 1024 npm run test:vc-compliance
