sudo: false
language: python
python:
  - "3.8"
install: pip install tox-travis
script: tox
after_success:
  - pip install python-semantic-release
  - git config user.name botcerts
  - git config user.email botcerts@learningmachine.com
  - semantic-release publish
after_script:
  - echo "chain=mockchain" >> conf.ini
  - cat conf.ini
  - pip install -r requirements.txt
  - npm ci
  - npm run test:vc-compliance
