sudo: false
language: python
python:
  - "3.8"
install: pip install tox-travis
script: tox
after_success:
  - pip install python-semantic-release
  - git config user.name botcerts
  - git config user.email botcerts@learningmachine.com
  - semantic-release publish
after_script:
  - sh prepare-compliance-tests-config.sh
  - python3 --version
  - which python3
  - which python
  - python3 setup.py install
  - npm ci
  - npm run test:vc-compliance
