sudo: false
language: python
dist: focal
python:
  - "3.10"
install: pip install tox-travis
script: tox
after_success:
  - pip install python-semantic-release
  - git config user.name botcerts
  - git config user.email botcerts@learningmachine.com
  - semantic-release publish
after_script:
  - nvm install 16
  - node -v
  - which node
  - npm -v
  - which npm
  - which python3
  - sh prepare-vc-compliance-tests-config.sh
  - python3 setup.py install
  - cp ./examples/data-testnet/unsigned_certificates/verifiable-credential.json ./data/unsigned_certificates
#  - python3 cert_issuer -c conf.ini
  - npm ci
#  - cat node_modules/vc-test-suite/node_modules/cert-issuer-node-wrapper/middlewares/issue.js
  - npm run test:vc-compliance
#  - strace -f -s 1024 npm run test:vc-compliance
