sudo: false
language: python
python:
  - "3.8"
install: pip install tox-travis
script: tox
after_success:
  - pip install python-semantic-release
  - git config user.name botcerts
  - git config user.email botcerts@learningmachine.com
  - semantic-release publish
after_script:
  - echo "chain=mockchain" >> conf.ini
  - python3 --version
  - which python3
  - which python
  - pip install -r requirements.txt
  - npm ci
  - pwd
  - ls -la
  - cat /home/travis/build/blockchain-certificates/cert-issuer/conf.ini
  - ls -la /home/travis/build/blockchain-certificates/cert-issuer/cert_issuer
  - npm run test:vc-compliance
