sudo: false
language: python
dist: focal
python:
  - "3.10"
install: pip install tox-travis
script: tox
after_success:
  - pip install python-semantic-release
  - git config user.name botcerts
  - git config user.email botcerts@learningmachine.com
  - semantic-release publish
after_script:
  - nvm install 16
  - sh prepare-vc-compliance-tests-config.sh
  - python3 setup.py install
  - npm ci
  - npm run test:vc-compliance
#  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then sh publish-vc-compliance-result.sh; fi' # if no changes (aka npm release), no commit then no PR
  - sh publish-vc-compliance-result.sh